### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by euthimius** [davrob01/AmazonBestSellerBooksScraper#2]
Dear David,

I just tested your cool AmazonBestSellerBooksScraper project but i am getting the following error.

No ISBNs are loaded.

Can you please advise

Thanks in advance
*********\* Log for 23 September 2016 22:20:57 **********

Starting process...

Failed to process page 1 of URL: http://www.amazon.com/best-sellers-books-Amazon/zgbs/books/
NullReferenceException
Object reference not set to an instance of an object.
   at AmazonBestSellers.DomainSlim.<RetrieveCategoryData>d__f.MoveNext()

Failed to process page 1 of URL: http://www.amazon.co.uk/gp/bestsellers/books/
NullReferenceException
Object reference not set to an instance of an object.
   at AmazonBestSellers.DomainSlim.<RetrieveCategoryData>d__f.MoveNext()

Failed to process page 1 of URL: http://www.amazon.it/gp/bestsellers/books/
NullReferenceException
Object reference not set to an instance of an object.
   at AmazonBestSellers.DomainSlim.<RetrieveCategoryData>d__f.MoveNext()

Failed to process page 1 of URL: http://www.amazon.fr/gp/bestsellers/english-books/
NullReferenceException
Object reference not set to an instance of an object.
   at AmazonBestSellers.DomainSlim.<RetrieveCategoryData>d__f.MoveNext()

Failed to process page 1 of URL: http://www.amazon.de/gp/bestsellers/books-intl-de/
NullReferenceException
Object reference not set to an instance of an object.
   at AmazonBestSellers.DomainSlim.<RetrieveCategoryData>d__f.MoveNext()

Failed to process page 1 of URL: http://www.amazon.co.jp/gp/bestsellers/english-books/
NullReferenceException
Object reference not set to an instance of an object.
   at AmazonBestSellers.DomainSlim.<RetrieveCategoryData>d__f.MoveNext()

Failed to process page 1 of URL: http://www.amazon.es/gp/bestsellers/foreign-books/
NullReferenceException
Object reference not set to an instance of an object.
   at AmazonBestSellers.DomainSlim.<RetrieveCategoryData>d__f.MoveNext()

Finished at 23 September 2016 22:20:59

**Comment by davrob01** [comment]
Looks like Amazon changed their protocol to https.

**Comment by davrob01** [comment]
This issue is resolved. Thank you!
