### ISSUE TITLE
No books are loaded

### ISSUE THREAD

**Issue by euthimius** [davrob01/AmazonBestSellerBooksScraper#4]
Dear David,

Your AmazonBestSellerBooksScraper.exe isn't working after the update.

No books are loaded nor in the test neither in the normal process. 

Log file remains blank.

**Comment by davrob01** [comment]
Hello euthimius,

Thank you for letting me know. It looks like Amazon has changed the way book nodes are represented, effecting the outcome of the scraper.

I have resolved this issue in commit [aa1cdc5c27ccb219334b7774b3939e22aa9c0534](https://github.com/davrob01/AmazonBestSellerBooksScraper/commit/aa1cdc5c27ccb219334b7774b3939e22aa9c0534)

Please re-download the scraper.

Thank you for your contribution!

-David
